USE codeup_test_db;
SELECT 'All albums by Pink Floyd' AS 'Caption';
SELECT name FROM albums WHERE artist = 'Pink Floyd';
SELECT 'Year Sgt. Peppers Lonely Hearts Club Band was released' AS 'Caption';
SELECT release_date FROM albums WHERE name = 'Sgt. Peppers Lonely Hearts Club Band';
SELECT 'Genre of Nevermind' AS 'Caption';
SELECT genre FROM albums WHERE name = 'Nevermind';
SELECT 'Albums released in the 1990s' AS 'Caption';
SELECT name FROM albums WHERE release_date BETWEEN 1990 AND 1999;
SELECT 'Albums with less than 20 million certified sales' AS 'Caption';
SELECT name FROM albums WHERE sales < 20;
SELECT 'Rock Albums' AS 'Caption';
SELECT name FROM albums WHERE genre = 'Rock';